export const formTemplate = {
	name: 'Name',
	surname: 'Surname',
	companyName: 'Company Name',
	documents: 'Documents and Passport Photograph',
	isIndividualCompany: 'Individual Company',
	isProprietorshipCompany: 'Proprietorship Company',
	isPartnershipCompany: 'Partnership Company',
	isLimitedCompany: 'Limited Company',
	officeAddress: 'Office Address',
	email: 'Email',
	website: 'Website',
	officePhone: 'Office Phone',
	mobilePhone: 'Mobile Phone',
	isDrivingLicense: 'Driving License',
	isVotersId: 'Voters ID',
	isInternationalPassport: 'International Passport',
	completed: 'Completed',
};
